1. [-] Move time operations into a chronometrist-time file
2. -report - highlight the current day

* Chronometrist
** Bugs
   1. Clocking-in/out doesn't result in updated display, sometimes (2019-09-12)
** Features
   1. Create chronometrist-unused-projects-list + chronometrist-projects-list.
   2. New commands
      * *Kill/discard* (bind to 'k') - which will delete the interval currently being recorded.
        - Most conservative option - it will only operate on the project at point, and will only kill for a clocked-in project.
        - Somewhat less conservative option - it will operate on the currently clocked-in project, no matter where point is.
        - It _should_ ask for confirmation.
        - Alternatively, or as a complement - an *undo command*, which will undo your last action (clock in or clock out).
      * *Convert* - change the currently clocked-in project to a different task. Tags and key-values may be re-queried. Clock-in hook functions will be run again with the new task as the argument.
      * *Rename* a project (updating all records)
      * *Delete* a project (erasing all records)
      * *Hide* a project (don't show it in any Chronometrist-* buffer, effectively deleting it non-destructively)
   3. Hook enhancement - can we supply the whole plist (including tags and key-values) to the task-start hooks, so users can have even smarter hook functions?
      * That would mean ensuring that -kv-read runs before other hooks.
      * Actually, it should be trivial to access the last expression in the file, so maybe this is unnecessary.
   4. Key-values
      * [-] generate history hash table from chronometrist-file.
        * [ ] generate value history hash table from chronometrist-file
        * [ ] handle ido, helm, ivy in -kv-read
      * [ ] if there are no previous key-values and user enters blank first key, cancel prompt and kill the key-value buffer
      * [ ] create button to add key-values to last entry (whether clocked in or out)
   5. Tags
      * [ ] generate history hash table from chronometrist-file
** UX
   1. don't suggest nil when asking for first project on first run
   2. when starting a project with time of "-" (i.e. not worked on today until now), immediately set time to 0 instead of waiting for the first timer refresh
   3. Mouse commands should work only on buttons.
   4. Button actions should accept prefix arguments and behave exactly like their keyboard counterparts.
   5. mouse-3 should clock-out without asking for reason.
   6. Some way to ask for the reason just before starting a project. Even when clocking out, the reason is asked /before/ clocking out, which adds time to the project.
   7. Allow calling chronometrist-in/out from anywhere-within-Emacs (a la timeclock) as well as from the chronometrist buffer.
*** Optimization
    ~chronometrist-refresh~ is expensive in CPU, and ~chronometrist-timer~ runs it every 3 seconds by default. :\

    (Note - actually, the most significant slowdown occurs when the file is changed /and/ the buffer is visible. When the file changes and the buffer isn't visible, it's relatively tolerable.)

**** Ideas
     * Support multiple files, so we read and process lesser data when one of them changes.
     * Make file writing async
     * Don't refresh from file when clocking in.
     * Only write to the file when Emacs is idle or being killed, and store data in memory (in the events hash table) in the meantime
     * What if commands both write to the file /and/ add to the hash table, so we don't have to re-read the file and re-populate the table for commands? The expensive reading+parsing could be avoided for commands, and only take place for the user changing the file.
** Code
   1. use variables instead of hardcoded numbers to determine spacing
   2. refactor repetitive calls to (format "%04d-%02d-%02d" (elt seq a) (elt seq b) (elt seq c))
   3. Use buttercup instead of ert
   4. See if it is possible to store buttons in a variable, so *-print-non-tabular functions can be made shorter and less imperative. (see ~make-text-button~)
   5. Merge all event-querying functions so that they always operate on an entire hash table (so no 'day' variants),
   +6. Timeclock already _has_ hooks! :| Why do we re-implement them?+
      - I don't know of a way to know the project being clocked into using timeclock hooks.
      - With v0.2.0 Chronometrist also has a before-project-stop-functions, which runs before the project is stopped, and can control whether the project actually is stopped.
